### ISSUE TITLE
Missing example app

### ISSUE THREAD

**Issue by lfarah** [delba/TextAttributes#1]
I really liked the library and I'd love if it had an example project showing the power of TextAttributes

**Comment by delba** [comment]
Thank you @lfarah 😃 

I chose not to include an example project in the repo as it's time consuming to maintain (update the Xcode version, answering to issues etc.) for little benefit (it's a very simple lib and it's really easy to get started with it).

I might include a playground though and I'll make sure to ping you on this thread.

Thanks again!

**Comment by neoneye** [comment]
Please reconsider @delba . This was what new potential users are looking for the first time.
