### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by jyounus** [delba/TextAttributes#13]
Hey there,

How would I make this work with ranges? Let's say my string is "Hello World". How would I change only the first 5 characters to be red coloured?

Thanks

**Comment by delba** [comment]
Hi @jyounus,

You're in luck, TextAttributes adds some convenient `NSAttributedString` extensions in [`AttributedString.swift`](https://github.com/delba/TextAttributes/blob/master/Source/AttributedString.swift)!

There are basically two ways of doing it:
- `func setAttributes(attributes: TextAttributes, range: Range<Int>)` [source](https://github.com/delba/TextAttributes/blob/master/Source/AttributedString.swift#L67)
- `func setAttributes(attributes: TextAttributes, range: NSRange)` [source](https://github.com/delba/TextAttributes/blob/master/Source/AttributedString.swift#L77)

Hope this helps!

**Comment by jyounus** [comment]
Perfect, thank you! You should probably consider adding that to the readme. :)
