### ISSUE TITLE
TextAttribtues reset paragraphStyle configured by InterfaceBuilder/Storyboard.

### ISSUE THREAD

**Issue by r-plus** [delba/TextAttributes#15]
Hi.

When migrate my project to TextAttributes I noticed problem and wrote patch for it that is `TextAttributes` reset paragraphStyle configured by storyboard even if not changed paragraphStyle parameter.

``` swift
// `@IBOutlet weak var label: UILabel!` is configured to center alignment via storyboard.

// Native: label is aligned to Center.
let attributedString = NSMutableAttributedString(string: "text")
attributedString.addAttribute(NSBaselineOffsetAttributeName, value: 8, range: NSRange(location: 0, length: 4))
label.attributedText = attributedString

// TextAttributes: label is aligned to Left.
let attributedString = NSMutableAttributedString(string: "text")
let attrs = TextAttributes().baselineOffset(8)
attributedString.addAttributes(attrs)
label.attributedText = attributedString
```

Is this bug or feature?

My workaround patch is this, but this patch break current TextAttributes behavior.
https://github.com/r-plus/TextAttributes/commit/680cf0786d0137c1e5bc114aa7d4ff845ecf84dc

P.S. I preferred current simply architecture. We should add `.alignment(.Center)` chain explicitly.

**Comment by delba** [comment]
Hi @r-plus , thanks for your feedback, I really appreciate it!

The example you gave isn't the correct translation of the native snippet though:

``` swift
let attributedString = NSMutableAttributedString(string: "text")
let attributes = TextAttributes().baselineOffset(8)
attributedString.addAttributes(attributes, range: NSRange(location: 0, length: 4))
```

Maybe the paragraphStyle configured by storyboard won't be reset if you add the attributes for a given range of the string ?

**Comment by r-plus** [comment]
Thanks for your response.

Try to change explicitly specify range, but no effect.

I publish sample project to reproduce for this issue.
https://github.com/r-plus/textattribute-test

**Comment by delba** [comment]
Hey @r-plus, I'm closing this issue. Let's say that TextAttributes doesn't play well with IB/Storyboard ;)
If we try to support this edge case, I bet it will be an endless task 😃

**Comment by r-plus** [comment]
I think so too.
