### ISSUE TITLE
How to set the range?

### ISSUE THREAD

**Issue by qiushuitian** [delba/TextAttributes#26]
I mean original function like this:
```
attributedString.setAttributes([NSFontAttributeName: UIFont.boldSystemFont(ofSize: 18)], range: dontRange)
```

**Comment by kmohsin11** [comment]
You can set range by calling the method setAttributes(attributes: TextAttributes , range:) 

let baseString = "Don't use magic numbers."
let attributedString = NSMutableAttributedString(string: baseString, attributes: nil)

let dontRange = (attributedString.string as NSString).range(of: "Don't")


let attr = TextAttributes()
            .font(UIFont.systemFont(ofSize: 10))
            .foregroundColor(.white)

attributedString.setAttributes(attr, range: dontRange)

**Comment by delba** [comment]
Thanks @kmohsin11 :)
