### ISSUE TITLE
Use underlineStyle(.single) cause crash app

### ISSUE THREAD

**Issue by daoan1412** [delba/TextAttributes#29]
App Error
`
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__SwiftValue _getValue:forType:]: unrecognized selector sent to instance 0x2807a3420'
`
Similar https://stackoverflow.com/questions/46092027/setting-nsunderlinestyle-causes-unrecogognized-selector-exception
Env: Xcode 11.2

**Comment by delba** [comment]
Hi @daoan1412, thank you so much, very good catch!
It has been fixed in `2.0.2` (the pod version is available) along with `strikethroughStyle` (see https://github.com/delba/TextAttributes/commit/ff5e84c544af9d362e5769ffd35b6c50944abc9b)
Thanks again :)
