### ISSUE TITLE
support Mac OS X

### ISSUE THREAD

**Issue by NilStack** [delba/TextAttributes#8]
hi, @delba :

Thanks for sharing TextAttributes
do you have plan to support Mac OS X?

thanks

**Comment by delba** [comment]
Hi @NilStack,

Thanks for the issue.
I won't consider TextAttributes to be complete without the support for OSX. So it's definitely on the roadmap!
Unfortunately it's a bit trickier / time consuming than some might think: there is more than just aliasing `UIFont` and `NSFont` to `Font`...

I'm gonna work on it this weekend but don't hold your breath ;)

Also, pull requests are welcome as always :)

**Comment by delba** [comment]
@NilStack I added the support for OSX on the [`next`](https://github.com/delba/TextAttributes/tree/next) branch.

Could you please check it out and report any bug please?

**Comment by NilStack** [comment]
@delba Thanks! I'm going to use it in my current project. Thanks for so quick response!
